name: 'tortellini-action'
description: 'GitHub Action that checks dependency licence issues using ort.'
author: 'Netherlands eScience Center'
inputs:
  repositories:
    required: false
    description: 'A file contains list of GitHub repository urls'
    default: 'urls.txt'
runs:
  using: 'node12'
  main: 'dist/index.js'
