name: testing
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          npm run package
      - run: |
          npm run test

  test-action: # make sure the action works on a clean machine without building
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ./
        - run: ls out/analyzer-result.yml
