name: testworkflow

on: # run any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  testworkflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo 'https://github.com/fair-software/howfairis' > urls.txt
      - uses: tortellini-tools/action@main
        with:
          repositories: urls.txt
      - run: tree -a -I '.git' -L 5 ./

      - run: ls -l .tortellini/out/fair-software/howfairis/analyzer-result.yml
      - run: |
        curl -o file.json -s http://145.100.59.103/tmp/gl-license-scanning-report.json
        diff file.json .tortellini/out/fair-software/howfairis/gl-license-scanning-report.json
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-results
          path: |
            .tortellini
            !.tortellini/in
            !.tortellini/out/**/analyzer-result.yml
            !.tortellini/out/**/evaluation-result.yml
