name: tortellini

on: # run any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: tortellini-tools/action@main
