name: tortellini

on: # run any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tortellini:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo 'https://github.com/tortellini-tools/action' > urls.txt
          echo 'https://github.com/fair-software/howfairis' >> urls.txt
      - uses: nelonoel/branch-name@v1.0.1
      - uses: tortellini-tools/action@neater-output
        with:
          repositories: 'urls.txt'
      - run: |
          tree -L 4 ./
