name: usage

on: # run any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  current-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tortellini-tools/action@main
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-result
          path: .tortellini/out

  multiple-repositories:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'https://github.com/tortellini-tools/action' > urls.txt
          echo 'https://github.com/fair-software/howfairis' >> urls.txt
      - uses: tortellini-tools/action@main
        with:
          repositories: urls.txt
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-results
          path: .tortellini/out
