name: usage on current repository

on: # run any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tortellini-tools/action@v3
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-result
          path: .tortellini/out
