name: usage on multiple repositories

on: # run any PRs and main branch changes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create list of GitHub urls to perform check on
        run: |
          echo 'https://github.com/tortellini-tools/action' > urls.txt
          echo 'https://github.com/fair-software/howfairis' >> urls.txt
      - uses: ./
        with:
          repositories: urls.txt
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-results
          path: .tortellini/out
